2025-07-04 19:28:04,507 INFO Running umol for TEST_LIG and TEST_PROT
2025-07-04 19:28:04,577 ERROR Failure: Command '['C:\\Python313\\python.exe', 'run_umol.py', '--protein', 'data/test_protein.pdb', '--ligand', 'data/test_ligand.sdf', '--output', 'data/output/poses/umol/TEST_LIG_TEST_PROT.pdb']' returned non-zero exit status 1.
2025-07-05 00:17:56,464 INFO Running umol for TEST_LIG and TEST_PROT
2025-07-05 00:17:56,621 INFO Success: data/output/poses/umol/TEST_LIG_TEST_PROT.pdb (runtime: 0.16s)
2025-07-05 00:18:33,693 INFO Running umol for TEST_LIG and TEST_PROT
2025-07-05 00:18:33,828 INFO Success: data/output/poses/umol/TEST_LIG_TEST_PROT.pdb (runtime: 0.14s)
2025-07-05 00:37:44,583 INFO Running umol for TEST_LIG and TEST_PROT
2025-07-05 00:37:44,714 INFO Success: data/output/poses/umol/TEST_LIG_TEST_PROT.pdb (runtime: 0.13s)
2025-07-05 00:44:36,321 INFO Running umol for TEST_LIG and TEST_PROT
2025-07-05 00:44:36,454 INFO Success: data/output/poses/umol/TEST_LIG_TEST_PROT.pdb (runtime: 0.13s)
